### ISSUE TITLE
Eventspage is not working

### ISSUE THREAD

**Issue by I-develop-bugs-for-a-living** [I-develop-bugs-for-a-living/DoroApp#9]
### Kind of static
Irgendwie tun Knöpfe nicht funktionieren

**Comment by I-develop-bugs-for-a-living** [comment]
🥺

**Comment by I-develop-bugs-for-a-living** [comment]
Ich hab doch garnichts getan.

**Comment by Benji4564** [comment]
![image](https://user-images.githubusercontent.com/63224938/231544630-04a7827b-a69d-487f-8af7-817eae10c874.png)
